export const books = [
  {
    id: 1,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 399,
    image: "/images/the-alchemist.jpg",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    price: 499,
    image: "/images/atomic-habits.jpg",
  },
  {
    id: 3,
    title: "Zero to One",
    author: "Peter Thiel",
    price: 350,
    image: "/images/zero-to-one.jpg",
  },
  {
    id: 4,
    title: "Ikigai",
    author: "Hector Garcia",
    price: 299,
    image: "/images/ikigai.jpg",
  },
  {
    id: 5,
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    price: 320,
    image: "/images/rich-dad-poor-dad.jpg",
  },
  {
    id: 6,
    title: "The Secret",
    author: "Rhonda Byrne",
    price: 280,
    image: "/images/the-secret.jpg",
  },
  {
    id: 7,
    title: "Wings of Fire",
    author: "A. P. J. Abdul Kalam",
    price: 299,
    image: "/images/wings-of-fire.jpg",
  },
  {
    id: 8,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: 340,
    image: "/images/think-and-grow-rich.jpg",
  },
  {
    id: 9,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 270,
    image: "/images/the-great-gatsby.jpg",
  },
  {
    id: 10,
    title: "The 5AM Club",
    author: "Robin Sharma",
    price: 399,
    image: "/images/the-5am-club.jpg",
  },
  {
    id: 11,
    title: "Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    price: 360,
    image: "/images/power-of-your-subconscious-mind.jpg",
  },
  {
    id: 12,
    title: "The Monk Who Sold His Ferrari",
    author: "Robin Sharma",
    price: 310,
    image: "/images/the-monk-who-sold-his-ferrari.jpg",
  }
];